version: '3'
services:
  # Rails application container
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  # PostgreSQL container using an official image
  db:
    image: postgres:latest
    environment:
    environment:
      POSTGRES_USER: level_up_in_life
      POSTGRES_PASSWORD: thegame
      POSTGRES_DB: level_up_in_life