version: '3'

services:
  # Rails application container
  web:
    build: .
    command: ["rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_USER: level_up_in_life
      POSTGRES_PASSWORD: gametime
      POSTGRES_DB: level_up_in_life_production

  # PostgreSQL database container
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: level_up_in_life
      POSTGRES_PASSWORD: gametime
      POSTGRES_DB: level_up_in_life_production
    ports:
      - "5432:5432"
