default: &default
  adapter: postgresql
  encoding: unicode
  username: level_up_in_life
  password: gametime
  host: db

production:
  <<: *default
  database: level_up_in_life_production

development:
  <<: *default
  database: level_up_in_life_development

test:
  <<: *default
  database: level_up_in_life_test