default: &default
  adapter: postgresql
  encoding: unicode
  username: level_up_in_life
  password: STMt62vzBEWXwJOEGUWqkVlX2HnlTEBA
  host: db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: level_up_in_life_development

test:
  <<: *default
  database: level_up_in_life_test